# Generated by Django 3.0.3 on 2020-03-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('profesion', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('creacion', models.DateField(auto_now_add=True)),
                ('editado', models.DateField(auto_now=True)),
            ],
        ),
    ]
